title: CV: Daniel Stanislaw
theme: minima
author: polono3000
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Just a place to share my designs and builds as a practicing licensed architect,
  a novice woodworker, and a sub-novice coder.
  
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
